### ISSUE TITLE
Applying get_hash function to .las data

### ISSUE THREAD

**Issue by Tojens** [themmes/pointcloud-example-notebooks#3]
Hi,

I went through the notebook in this repo in an attempt to preprocess my own .las files with the intent of running pointnet. I am not having any luck getting the grid/hash operation to run. 

More specifically:
df['hash'] = df[['X', 'Y']].apply(get_hash, grid_size=grid_size, meta=('hash', int), axis=1) 

runs with no errors, but as I try to run df.to_parquet it is returning the error:

invalid value for result_type, must be one of {None, 'reduce', 'broadcast', 'expand'}

I'm afraid I can't seem to solve this on my own, so any help would be appreciated.

I've tried setting up an environment as it would have been when the notebook was made, but it did not help very much.

Regards

**Comment by themmes** [comment]
Hi Tobias,

Thanks for your issue!

To provide some context, I used the Morton code here to create an identifier that would give points within the same cell the same id. So its a way to split the data and identify.

When trying to reproduce my code I stumble upon the following error:

```
/usr/local/lib/python3.7/site-packages/morton.py in split(self, value)
     52         lshifts = self.lshifts
     53         for o in range(len(masks)):
---> 54             value = (value | (value << lshifts[o])) & masks[o]
     55         return value
     56

TypeError: ("ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''", 'occurred at index 0')
```

Is this the same error you were getting?

**Comment by Tojens** [comment]
Yes that is exactly it!

Do you have any suggestions as to how this might be fixed? :)

**Comment by themmes** [comment]
The problem is with the `point.x // grid_size` this returns a `float`, while `Morton.pack()` expects an `integer`.

Please change the `get_hash()` function to the following:\

```
In [34]: def get_hash(point, grid_size=grid_size):
    ...:     return m.pack(int(point.x // grid_size), int(point.y // grid_size))

In [35]: df[['x', 'y']].apply(get_hash, grid_size=5, axis=1)
Out[35]:
0      51288
1      26852
2      50245
3      51772
4      20439
```

That should do the trick!

(PS. I would love if you turn this into a PR)

**Comment by Tojens** [comment]
Thanks so much for the help. It solved the problem! 

I created a pull request (first one ever, so if I did anything wrong, please say so)
